# Test the Python product-service

### Get list of products
GET http://localhost:3030/products
Accept: application/json

### Health check
GET http://localhost:3030/health
Accept: application/json

### Test with different port (if PORT environment variable is set)
GET http://localhost:8000/products
Accept: application/json
